name: google_maps_in_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  http: ^0.13.5
  json_serializable: ^6.6.1
  geolocator: ^9.0.2
  dio: ^5.1.1
  cookie_jar: ^4.0.2
  axios: ^0.0.1
  dio_cookie_manager: ^3.0.0
  shelf_proxy: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/locations.json
    - assets/images/ya.jpg